// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKnneBFMazwP8wb-hf7bHmsR1Pta1zI14',
    appId: '1:137510836410:web:ae770d3abed651fb8b8a83',
    messagingSenderId: '137510836410',
    projectId: 'finance-manager-2e11e',
    authDomain: 'finance-manager-2e11e.firebaseapp.com',
    storageBucket: 'finance-manager-2e11e.appspot.com',
    measurementId: 'G-F67X2XT0T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL_9LqpyNo7CvmlgR0raG9VfkKyAwBnnA',
    appId: '1:137510836410:android:3187d5436af889138b8a83',
    messagingSenderId: '137510836410',
    projectId: 'finance-manager-2e11e',
    storageBucket: 'finance-manager-2e11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4RPgxyZhkYBG3jCMh-Jtnr74cjsdgz2w',
    appId: '1:137510836410:ios:00a74259074468ed8b8a83',
    messagingSenderId: '137510836410',
    projectId: 'finance-manager-2e11e',
    storageBucket: 'finance-manager-2e11e.appspot.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4RPgxyZhkYBG3jCMh-Jtnr74cjsdgz2w',
    appId: '1:137510836410:ios:00a74259074468ed8b8a83',
    messagingSenderId: '137510836410',
    projectId: 'finance-manager-2e11e',
    storageBucket: 'finance-manager-2e11e.appspot.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKnneBFMazwP8wb-hf7bHmsR1Pta1zI14',
    appId: '1:137510836410:web:fb845eaf385c0be88b8a83',
    messagingSenderId: '137510836410',
    projectId: 'finance-manager-2e11e',
    authDomain: 'finance-manager-2e11e.firebaseapp.com',
    storageBucket: 'finance-manager-2e11e.appspot.com',
    measurementId: 'G-BZ7X2XY4H2',
  );
}
